### ISSUE TITLE
overall find_anaemia function will not work if dataset is a mixed dataset

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/nutricheckr#41]
Current `find_anaemia` function will not work properly when dataset provided has a mix of population groupings.

Might be good to refactor the function such that it will only use one of the groups for determining anaemia.

**Comment by nicholustintzaw** [comment]
cloned refactor package and created new branched 'refactor_pkg_ncl'. Then, developed a new function to consider for the mix-pop dataset. Please check in the new pull request.
