### ISSUE TITLE
qualitative function for detecting iron deficiency anaemia needs correcting

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/nutricheckr#43]
The cutoff for ferritin of 30 is only for when there is inflammation. Without knowledge of inflammation, we can't determine iron status. So, should be NA.

**Comment by nicholustintzaw** [comment]
modified the qualitative function as if the infection variable value is FALSe (logical value), apply the function. In the previous version, treated as NA_character_. Please see the new pull request.
